name: Package CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.0.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Run the CI
        run: npm run ci

      - name: Run the tests
        run: npm run test

      - name: Run the lint
        run: npm run lint

      - name: Size limit
        run: npm run size-limit